default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: weather_app_development
  username:
  password:

production:
  <<: *default
  database: weather_app_production
  username: 
  password:
