default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  host: ec2-174-129-227-146.compute-1.amazonaws.com
  database: d90he2an0b4uac
  username: flhrrvnpdrpouh
  password: f840afd8d6fbefe6fbb198836255900b3855f03c71f8b2f25f99a63de1082be5

development:
  <<: *default
  host: localhost
  database: weather_app_development
  username: postgres
  password: postgres
